#!/bin/bash

# This script will attempt to read in the Remote IP config from the
#  ENV var and apply the settings in the matching remoteip.conf file.
#
# APACHE_TRUSTED_PROXIES="10.0.0.0/23,172.16.10.0/24"
#

if [ -d "/etc/apache2/conf-available" ]; then

    # Configure Apache's RemoteIP Module
    {
        # Read more about the remoteip module here:
        #  https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html
        echo "RemoteIPHeader X-Forwarded-For"
        # echo "RemoteIPTrustedProxy ${APACHE_TRUSTED_PROXIES//[;,]/ }"
        echo "RemoteIPInternalProxy ${APACHE_TRUSTED_PROXIES//[;,]/ }"
    } >/etc/apache2/conf-available/remoteip.conf

fi
