name: Test Building Docker Images

permissions:
  contents: read

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "README.md"
      - "docker-compose.yml"
      - "examples/**"
      - ".run/**"
      - ".circleci/**"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.platform }} ${{ matrix.variant }} ${{ matrix.php_version }}
    runs-on: ${{ matrix.target.runner }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        php_version: ['8.5'] # , '8.4', '8.3', '8.1', '8.0']
        variant: ['apache', 'apache-chrome']
        target:
          - platform: linux/amd64
            runner: ubuntu-24.04 # ubuntu-latest
          - platform: linux/arm64
            runner: ubuntu-24.04-arm # ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Github Short SHA
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV

      - name: Set variables
        run: |
          if [ "${{ matrix.variant }}" == "apache" ]; then
            echo "DOCKER_TAG=pr_${{ github.event.number }}_${{ matrix.php_version }}" >> $GITHUB_ENV
            echo "DOCKER_FILE=Dockerfile" >> $GITHUB_ENV
          elif [ "${{ matrix.variant }}" == "apache-chrome" ]; then
            echo "DOCKER_TAG=pr_${{ github.event.number }}_${{ matrix.php_version }}-headless" >> $GITHUB_ENV
            echo "DOCKER_FILE=Dockerfile-headless" >> $GITHUB_ENV
          else
            echo "Invalid variant: ${{ matrix.variant }}"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          # list of Docker images to use as base name for tags
          images: |

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./aio/${{ env.DOCKER_FILE }}
          tags:
            ghcr.io/${{ github.repository }}:${{ env.DOCKER_TAG }},
            ghcr.io/${{ github.repository }}:${{ env.GITHUB_SHA_SHORT }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          push: false
          provenance: mode=max
          platforms: ${{ matrix.target.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
